ln -sf ~/.config/zsh/.zshenv ~/.zshenv
ln -sf ~/.config/zsh/.zshrc ~/.zshrc
ln -sf ~/.config/.bashrc ~/.bashrc
ln -sf ~/.config/tmux/.tmux.conf ~/.tmux.conf
ln -sf ~/.config/.gitconfig ~/.gitconfig
ln -sf ~/.config/.gitignore ~/.gitignore
ln -sf ~/.config/.vimrc ~/.vimrc
ln -sf ~/.config/.yarnrc ~/.yarnrc
ln -sf ~/.config/.npmrc ~/.npmrc
ln -sf ~/.config/.macos ~/.macos
ln -sf ~/.config/.macos ~/.macos
